"""GitHub service -- creates branches, commits YAML configs, and opens PRs."""

from __future__ import annotations

import logging
import uuid as _uuid

from github import Github, GithubException

from backend.config import get_settings

logger = logging.getLogger(__name__)


def _client() -> Github:
    settings = get_settings()
    return Github(settings.github_token)


def _repo():
    settings = get_settings()
    return _client().get_repo(settings.github_repo)


def create_product_pr(
    product_name: str,
    domain: str,
    yaml_content: str,
    created_by: str,
    classification: str,
) -> str:
    """Create a branch, commit the product YAML, and open a PR. Returns the PR URL."""
    repo = _repo()
    settings = get_settings()
    short_id = str(_uuid.uuid4())[:8]
    branch_name = f"dpvm/create-{product_name}-{short_id}"

    base_ref = repo.get_git_ref(f"heads/{settings.github_base_branch}")
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_ref.object.sha)

    file_path = f"configs/{domain}/{product_name}.yaml"
    repo.create_file(
        path=file_path,
        message=f"dpvm: create data product '{product_name}'",
        content=yaml_content,
        branch=branch_name,
    )

    pr = repo.create_pull(
        title=f"[DPVM] Create data product: {product_name}",
        body=(
            f"## Data Product Provisioning Request\n\n"
            f"- **Product:** {product_name}\n"
            f"- **Domain:** {domain}\n"
            f"- **Classification:** {classification}\n"
            f"- **Requested by:** {created_by}\n\n"
            f"This PR was auto-generated by the Data Product Vending Machine.\n"
            f"Merge to trigger Terraform provisioning."
        ),
        head=branch_name,
        base=settings.github_base_branch,
    )

    logger.info("Created PR %s for product %s", pr.html_url, product_name)
    return pr.html_url


def update_product_pr(
    product_name: str,
    domain: str,
    yaml_content: str,
    commit_message: str,
    pr_title: str,
    pr_body: str,
) -> str:
    """Update an existing config file via a new PR. Returns the PR URL."""
    repo = _repo()
    settings = get_settings()
    short_id = str(_uuid.uuid4())[:8]
    branch_name = f"dpvm/update-{product_name}-{short_id}"

    base_ref = repo.get_git_ref(f"heads/{settings.github_base_branch}")
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_ref.object.sha)

    file_path = f"configs/{domain}/{product_name}.yaml"

    try:
        existing = repo.get_contents(file_path, ref=settings.github_base_branch)
        repo.update_file(
            path=file_path,
            message=commit_message,
            content=yaml_content,
            sha=existing.sha,
            branch=branch_name,
        )
    except GithubException:
        repo.create_file(
            path=file_path,
            message=commit_message,
            content=yaml_content,
            branch=branch_name,
        )

    pr = repo.create_pull(
        title=pr_title,
        body=pr_body,
        head=branch_name,
        base=settings.github_base_branch,
    )

    logger.info("Created update PR %s for product %s", pr.html_url, product_name)
    return pr.html_url


def get_config_content(domain: str, product_name: str) -> str | None:
    """Fetch the current YAML config from the main branch."""
    repo = _repo()
    settings = get_settings()
    file_path = f"configs/{domain}/{product_name}.yaml"
    try:
        content = repo.get_contents(file_path, ref=settings.github_base_branch)
        return content.decoded_content.decode("utf-8")
    except GithubException:
        return None
